# Generated by Django 5.2.17 on 2026-09-23 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orcid', models.CharField(blank=True, max_length=40, verbose_name='ORCID')),
                ('first_name', models.CharField(blank=True, max_length=200)),
                ('last_name', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'author (person)',
                'verbose_name_plural': 'authors (people)',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='LinkCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'link categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_edited_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('number', models.PositiveIntegerField(unique=True, verbose_name='conference number')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=200)),
                ('country', models.CharField(blank=True, max_length=200)),
                ('conference_title', models.CharField(blank=True, max_length=500)),
                ('proceedings_title', models.CharField(blank=True, max_length=500)),
                ('publisher', models.CharField(blank=True, max_length=300)),
                ('publication_location', models.CharField(blank=True, max_length=300)),
                ('issn', models.CharField(blank=True, max_length=20, verbose_name='ISSN')),
                ('is_published', models.BooleanField(default=False, verbose_name='published on website')),
                ('last_edited_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-number'],
            },
        ),
        migrations.CreateModel(
            name='ConferenceTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='archive.conference')),
            ],
            options={
                'ordering': ['conference', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Editor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=200)),
                ('last_name', models.CharField(blank=True, max_length=200)),
                ('title_and_contact', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(blank=True, null=True)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editors', to='archive.conference')),
            ],
            options={
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('url', models.URLField(max_length=1000)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.IntegerField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='archive.linkcategory')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_edited_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('title', models.TextField()),
                ('abstract', models.TextField(blank=True)),
                ('keywords', models.TextField(blank=True)),
                ('first_page', models.PositiveIntegerField(blank=True, null=True)),
                ('last_page', models.PositiveIntegerField(blank=True, null=True)),
                ('doi', models.CharField(blank=True, max_length=200, verbose_name='DOI')),
                ('full_text_url', models.URLField(blank=True, max_length=1000, verbose_name='full text (PDF) URL')),
                ('a3_url', models.URLField(blank=True, max_length=1000, verbose_name='A3 URL')),
                ('presentation_url', models.URLField(blank=True, max_length=1000)),
                ('status', models.IntegerField(choices=[(0, 'New'), (1, 'Imported'), (2, 'Editing'), (3, 'Finalised'), (4, 'Approved')], default=0)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='papers', to='archive.conference')),
                ('last_edited_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='papers', to='archive.conferencetrack')),
            ],
            options={
                'ordering': ['conference', models.OrderBy(models.F('first_page'), nulls_last=True), 'title'],
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=200)),
                ('last_name', models.CharField(blank=True, max_length=200)),
                ('title_and_contact', models.TextField(blank=True, verbose_name='affiliation and contact')),
                ('order', models.PositiveIntegerField(blank=True, null=True)),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorships', to='archive.authorperson')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='archive.paper')),
            ],
            options={
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_edited_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('number', models.PositiveIntegerField(verbose_name='volume number')),
                ('first_page', models.PositiveIntegerField()),
                ('last_page', models.PositiveIntegerField()),
                ('isbn', models.CharField(blank=True, max_length=30, verbose_name='ISBN')),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volumes', to='archive.conference')),
                ('last_edited_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['conference', 'number'],
            },
        ),
        migrations.AddField(
            model_name='paper',
            name='volume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='papers', to='archive.volume'),
        ),
        migrations.AddIndex(
            model_name='paper',
            index=models.Index(fields=['doi'], name='archive_pap_doi_0fd3c6_idx'),
        ),
    ]
