# Generated by Django 5.2.17 on 2026-09-23 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='papers_zip_url',
            field=models.URLField(blank=True, help_text='Link to a ZIP file with every paper, shown on the conference page.', max_length=1000, verbose_name='ZIP of all papers'),
        ),
        migrations.CreateModel(
            name='ProceedingsFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="For example 'Full proceedings' or 'Volume 1'.", max_length=100)),
                ('url', models.URLField(max_length=1000)),
                ('order', models.PositiveIntegerField(default=1)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proceedings_files', to='archive.conference')),
            ],
            options={
                'ordering': ['conference', 'order'],
            },
        ),
    ]
