# Generated by Django 5.2.17 on 2026-09-23 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0002_conference_papers_zip_url_proceedingsfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='authors_text',
            field=models.TextField(blank=True, editable=False, help_text='All author names, kept up to date automatically, used by search.'),
        ),
    ]
