# Generated by Django 5.2.17 on 2026-09-24 07:03

from django.db import migrations, models


def single_names_as_last_names(apps, schema_editor):
    for name in ("Author", "AuthorPerson", "Editor"):
        model = apps.get_model("archive", name)
        for obj in model.objects.filter(last_name="").exclude(first_name=""):
            model.objects.filter(pk=obj.pk).update(first_name="", last_name=obj.first_name.strip())


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0005_unescape_html_entities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='last_name',
            field=models.CharField(blank=True, help_text='For a person with a single name, put it here and leave the first name empty.', max_length=200),
        ),
        migrations.AlterField(
            model_name='authorperson',
            name='last_name',
            field=models.CharField(blank=True, help_text='For a person with a single name, put it here and leave the first name empty.', max_length=200),
        ),
        migrations.AlterField(
            model_name='editor',
            name='last_name',
            field=models.CharField(blank=True, help_text='For a person with a single name, put it here and leave the first name empty.', max_length=200),
        ),
        migrations.RunPython(single_names_as_last_names, migrations.RunPython.noop),
    ]
