# Generated by Django 5.2.17 on 2026-09-24 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0006_single_names'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conferencetrack',
            options={'ordering': ['conference', 'order', 'title']},
        ),
        migrations.AddField(
            model_name='conferencetrack',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Position of the track in the proceedings.'),
        ),
    ]
