# Generated by Django 5.2.17 on 2026-09-24 13:16

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0009_tracks_from_papers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='paper',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='archive.paper'),
        ),
        migrations.AlterField(
            model_name='conferencetrack',
            name='conference',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='archive.conference'),
        ),
        migrations.AlterField(
            model_name='editor',
            name='conference',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='editors', to='archive.conference'),
        ),
        migrations.AlterField(
            model_name='link',
            name='category',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='archive.linkcategory'),
        ),
        migrations.AlterField(
            model_name='proceedingsfile',
            name='conference',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='proceedings_files', to='archive.conference'),
        ),
        migrations.AlterField(
            model_name='volume',
            name='conference',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='volumes', to='archive.conference'),
        ),
    ]
