# Generated by Django 5.2.17 on 2026-09-25 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archive", "0010_admin_clusters"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conference",
            name="is_published",
            field=models.BooleanField(
                default=False,
                help_text="The conference and its papers are listed in the public archive, the search and the exports. Publishing through Proceedings production ticks it. (Not the conference website.)",
                verbose_name="proceedings in the archive",
            ),
        ),
    ]
