# Generated by Django 5.2.17 on 2026-09-26 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archive", "0011_proceedings_in_archive_label"),
    ]

    operations = [
        migrations.AddField(
            model_name="conference",
            name="website_placeholder",
            field=models.BooleanField(
                default=False,
                help_text="Until the conference's website is published, its address (conference site /<year>/) shows a simple page: the conference's name, place, dates, logo and contact address.",
                verbose_name="placeholder website",
            ),
        ),
    ]
