# Generated by Django 5.2.17 on 2026-09-24 07:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaperCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('stage', models.CharField(max_length=20)),
                ('file_name', models.CharField(max_length=255)),
                ('sha256', models.CharField(max_length=64, verbose_name='SHA-256 of the Word file')),
                ('pdf_sha256', models.CharField(blank=True, max_length=64, verbose_name='SHA-256 of the PDF')),
                ('title', models.CharField(blank=True, max_length=500)),
                ('passed', models.BooleanField()),
                ('findings', models.JSONField(default=list)),
            ],
            options={
                'verbose_name': 'paper check',
                'ordering': ['-created'],
            },
        ),
    ]
