# Generated by Django 5.2.17 on 2026-09-24 08:36

import apps.production.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0007_track_order'),
        ('production', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProceedingsVolume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('collecting', 'Collecting and editing papers'), ('arranging', 'Arranging (order and page numbers)'), ('published', 'Published')], default='collecting', max_length=20)),
                ('first_page', models.PositiveIntegerField(default=1, help_text='Page number of the first paper.')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('conference', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='production', to='archive.conference')),
            ],
            options={
                'verbose_name': 'proceedings volume',
                'ordering': ['-conference__number'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conftool_id', models.PositiveIntegerField(verbose_name='ConfTool ID')),
                ('title', models.CharField(help_text='As registered (ConfTool); the published title comes from the paper.', max_length=500)),
                ('registered_authors', models.JSONField(blank=True, default=list, help_text='Authors as registered (ConfTool): name, organisation, email. Used to contact them.')),
                ('status', models.CharField(choices=[('waiting', 'Waiting for the edited paper'), ('uploaded', 'Uploaded, to be checked'), ('needs_work', 'Needs more work'), ('approved', 'Approved'), ('withdrawn', 'Withdrawn')], default='waiting', max_length=20)),
                ('position', models.PositiveIntegerField(default=0, help_text='Order within the track.')),
                ('first_page', models.PositiveIntegerField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_submissions', to=settings.AUTH_USER_MODEL)),
                ('paper', models.OneToOneField(blank=True, help_text='The published paper, once published.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submission', to='archive.paper')),
                ('track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='archive.conferencetrack')),
                ('volume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='production.proceedingsvolume')),
            ],
            options={
                'ordering': ['volume', 'track__order', 'position', 'conftool_id'],
                'unique_together': {('volume', 'conftool_id')},
            },
        ),
        migrations.CreateModel(
            name='PaperVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(blank=True)),
                ('docx', models.FileField(upload_to=apps.production.models._version_path)),
                ('docx_sha256', models.CharField(max_length=64)),
                ('pdf', models.FileField(blank=True, upload_to=apps.production.models._version_path)),
                ('pdf_sha256', models.CharField(blank=True, max_length=64)),
                ('pages', models.PositiveIntegerField(blank=True, help_text='From the PDF.', null=True)),
                ('metadata', models.JSONField(default=dict, help_text='What was read from the Word file.')),
                ('findings', models.JSONField(default=list, help_text='The template check.')),
                ('passed', models.BooleanField(default=False)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='production.submission')),
            ],
            options={
                'ordering': ['submission', '-number'],
                'unique_together': {('submission', 'number')},
            },
        ),
        migrations.CreateModel(
            name='VolumeEditor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('chief', 'Chief editor'), ('editor', 'Editor')], default='editor', max_length=10)),
                ('tracks', models.ManyToManyField(blank=True, to='archive.conferencetrack')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volume_roles', to=settings.AUTH_USER_MODEL)),
                ('volume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editors', to='production.proceedingsvolume')),
            ],
            options={
                'unique_together': {('volume', 'user')},
            },
        ),
    ]
