# Generated by Django 5.2.17 on 2026-09-24 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_rename_to_production'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='status',
            field=models.CharField(choices=[('collecting', 'Collecting and editing papers'), ('arranging', 'Arranging (order and page numbers)'), ('papers_published', 'Papers published'), ('complete', 'Full proceedings published')], default='collecting', max_length=20),
        ),
    ]
