# Generated by Django 5.2.17 on 2026-09-24 08:54

import apps.production.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_two_stage_publication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paperversion',
            name='docx',
            field=models.FileField(storage=apps.production.models.private_storage, upload_to=apps.production.models._version_path),
        ),
        migrations.AlterField(
            model_name='paperversion',
            name='pdf',
            field=models.FileField(blank=True, storage=apps.production.models.private_storage, upload_to=apps.production.models._version_path),
        ),
    ]
