# Generated by Django 5.2.17 on 2026-09-24 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0006_events'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='published_pdf',
            field=models.FileField(blank=True, help_text='The published PDF (public), with running headers and page numbers.', max_length=300, upload_to='papers/'),
        ),
        migrations.AddField(
            model_name='submission',
            name='published_version',
            field=models.ForeignKey(blank=True, help_text='The version whose PDF is on the site.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='production.paperversion'),
        ),
        migrations.CreateModel(
            name='Correction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(help_text="What was corrected. Shown on the paper's page.")),
                ('previous_pdf', models.CharField(blank=True, help_text='The PDF that was replaced (kept).', max_length=300)),
                ('previous_version', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='production.paperversion')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrections', to='production.submission')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='production.paperversion')),
            ],
            options={
                'ordering': ['time'],
            },
        ),
    ]
