# Generated by Django 5.2.17 on 2026-09-24 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0007_publication'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='metadata_edits',
            field=models.JSONField(blank=True, default=dict, help_text="The editors' corrections to what is read from the Word file: the title in sentence case and how names split into first and last name."),
        ),
    ]
