# Generated by Django 5.2.17 on 2026-09-24 10:32

import apps.production.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0007_track_order'),
        ('production', '0008_metadata_edits'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='production',
            options={'ordering': ['-conference__number'], 'permissions': [('publish_production', 'Can approve publication and set ISBNs (publisher)')], 'verbose_name': 'proceedings production'},
        ),
        migrations.AddField(
            model_name='production',
            name='book',
            field=models.FileField(blank=True, help_text='The published full proceedings PDF.', max_length=300, upload_to='proceedings/'),
        ),
        migrations.AddField(
            model_name='production',
            name='book_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='production',
            name='book_requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='production',
            name='conference_chair',
            field=models.CharField(blank=True, help_text='Printed on the title page.', max_length=300),
        ),
        migrations.AddField(
            model_name='production',
            name='copyright_holders',
            field=models.CharField(blank=True, help_text='For the colophon; the editors if empty.', max_length=500),
        ),
        migrations.AddField(
            model_name='production',
            name='draft_built',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='production',
            name='isbn_pdf',
            field=models.CharField(blank=True, max_length=30, verbose_name='ISBN (PDF)'),
        ),
        migrations.AddField(
            model_name='production',
            name='isbn_print',
            field=models.CharField(blank=True, max_length=30, verbose_name='ISBN (printed)'),
        ),
        migrations.AddField(
            model_name='production',
            name='issn_electronic',
            field=models.CharField(blank=True, default='2789-0015', max_length=20, verbose_name='ISSN (electronic)'),
        ),
        migrations.AddField(
            model_name='production',
            name='issn_print',
            field=models.CharField(blank=True, default='2309-0979', max_length=20, verbose_name='ISSN (printed)'),
        ),
        migrations.AddField(
            model_name='production',
            name='papers_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='production',
            name='papers_requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='submission',
            name='correction_note',
            field=models.TextField(blank=True, help_text='A correction waiting for the publisher.'),
        ),
        migrations.AddField(
            model_name='submission',
            name='correction_requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='BookPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('cover', 'Front cover'), ('organisation', 'Conference organisation'), ('foreword', 'Foreword'), ('reviewers', 'List of reviewers'), ('other', 'Other front matter'), ('back_cover', 'Back cover')], max_length=20)),
                ('title', models.CharField(blank=True, help_text="For 'other': the heading, used in the bookmarks.", max_length=200)),
                ('pdf', models.FileField(storage=apps.production.models.private_storage, upload_to=apps.production.models._part_path)),
                ('pages', models.PositiveIntegerField(default=0)),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_parts', to='production.production')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['production', 'uploaded'],
            },
        ),
        migrations.CreateModel(
            name='TrackChair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('affiliation', models.CharField(blank=True, max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_chairs', to='production.production')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chairs', to='archive.conferencetrack')),
            ],
            options={
                'ordering': ['track__order', 'order', 'name'],
            },
        ),
    ]
