# Generated by Django 5.2.17 on 2026-09-24 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0009_full_proceedings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookpart',
            options={'ordering': ['production', 'placement', 'order', 'uploaded']},
        ),
        migrations.AddField(
            model_name='bookpart',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bookpart',
            name='placement',
            field=models.CharField(choices=[('front', 'Front matter (before the contents)'), ('back', 'Back matter (after the author index)')], default='front', max_length=10),
        ),
        migrations.AlterField(
            model_name='bookpart',
            name='kind',
            field=models.CharField(choices=[('cover', 'Front cover'), ('organisation', 'Conference organisation'), ('message', 'Message (e.g. from the conference chair)'), ('foreword', 'Foreword'), ('reviewers', 'List of reviewers'), ('sponsors', 'Sponsors'), ('other', 'Other section'), ('back_cover', 'Back cover')], help_text='Which template it is made from.', max_length=20),
        ),
        migrations.AlterField(
            model_name='bookpart',
            name='title',
            field=models.CharField(blank=True, help_text='The heading, for the bookmarks.', max_length=200),
        ),
    ]
