# Generated by Django 5.2.17 on 2026-09-24 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0010_book_sections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='action',
            field=models.CharField(max_length=200),
        ),
    ]
