# Generated by Django 5.2.17 on 2026-09-24 13:16

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0010_admin_clusters'),
        ('production', '0011_longer_event_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productioneditor',
            name='production',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='editors', to='production.production'),
        ),
        migrations.AlterField(
            model_name='productioneditor',
            name='tracks',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='archive.conferencetrack'),
        ),
    ]
