# Generated by Django 5.2.17 on 2026-09-24 14:10

import apps.production.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0012_admin_clusters'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='correction_pdf',
            field=models.FileField(blank=True, help_text='For a paper published before these tools: the replacement PDF, waiting for the publisher.', max_length=300, storage=apps.production.models.private_storage, upload_to=apps.production.models._correction_path),
        ),
        migrations.AlterField(
            model_name='correction',
            name='version',
            field=models.ForeignKey(blank=True, help_text='Empty for a paper published before these tools (its PDF was replaced).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='production.paperversion'),
        ),
    ]
