# Generated by Django 5.2.17 on 2026-09-24 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0013_pdf_corrections'),
    ]

    operations = [
        migrations.AddField(
            model_name='correction',
            name='public',
            field=models.BooleanField(default=False, help_text="Show the note on the paper's page. Worth it for a substantial change long after publication; noise for a small fix soon after."),
        ),
        migrations.AddField(
            model_name='submission',
            name='correction_public',
            field=models.BooleanField(default=False, help_text="Whether its note is to be shown on the paper's page."),
        ),
        migrations.AlterField(
            model_name='correction',
            name='note',
            field=models.TextField(help_text='What was corrected (kept for the record).'),
        ),
    ]
