# Generated by Django 5.2.17 on 2026-09-24 15:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0014_correction_public'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetadataCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('recipients', models.JSONField(default=list)),
                ('deadline', models.DateField()),
                ('reminded', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('sent', 'Waiting for the authors'), ('confirmed', 'Confirmed by the authors'), ('corrections', 'Corrections proposed'), ('handled', 'Corrections handled')], default='sent', max_length=20)),
                ('responded', models.DateTimeField(blank=True, null=True)),
                ('responder', models.CharField(blank=True, help_text='Who answered (as they gave their name).', max_length=200)),
                ('proposal', models.JSONField(blank=True, default=dict, help_text='The corrections: title, authors, comment.')),
                ('handled', models.DateTimeField(blank=True, null=True)),
                ('handled_note', models.TextField(blank=True)),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sent_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metadata_checks', to='production.submission')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
