# Generated by Django 5.2.17 on 2026-09-24 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0015_metadata_check"),
    ]

    operations = [
        migrations.CreateModel(
            name="CheckLimits",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "max_pages",
                    models.PositiveIntegerField(
                        default=12,
                        help_text="Without the submission checklist.",
                        verbose_name="maximum pages",
                    ),
                ),
                (
                    "title_chars",
                    models.PositiveIntegerField(
                        default=90, verbose_name="maximum title length (characters)"
                    ),
                ),
                (
                    "abstract_words",
                    models.PositiveIntegerField(
                        default=200, verbose_name="maximum abstract length (words)"
                    ),
                ),
                (
                    "keywords",
                    models.PositiveIntegerField(
                        default=5, verbose_name="maximum keywords"
                    ),
                ),
                (
                    "manual_formatting",
                    models.PositiveIntegerField(
                        default=10,
                        help_text="Pieces of text (or paragraphs) formatted by hand before it is reported. A few are normal (a symbol, a superscript size).",
                        verbose_name="formatting set by hand: report from",
                    ),
                ),
            ],
            options={
                "verbose_name": "paper check limits",
            },
        ),
        migrations.CreateModel(
            name="CheckRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(editable=False, max_length=60, unique=True)),
                ("label", models.CharField(editable=False, max_length=200)),
                (
                    "review",
                    models.CharField(
                        choices=[
                            ("off", "Off"),
                            ("note", "Note"),
                            ("warn", "Warn"),
                            ("reject", "Reject"),
                        ],
                        help_text="Full and revised papers under review (anonymous).",
                        max_length=10,
                        verbose_name="paper for review",
                    ),
                ),
                (
                    "camera_ready",
                    models.CharField(
                        choices=[
                            ("off", "Off"),
                            ("note", "Note"),
                            ("warn", "Warn"),
                            ("reject", "Reject"),
                        ],
                        help_text="The authors' camera-ready paper.",
                        max_length=10,
                        verbose_name="camera-ready paper",
                    ),
                ),
                (
                    "production",
                    models.CharField(
                        choices=[
                            ("off", "Off"),
                            ("note", "Note"),
                            ("warn", "Warn"),
                            ("reject", "Reject"),
                        ],
                        help_text="The proceedings editors' uploads (Word file and PDF).",
                        max_length=10,
                        verbose_name="editors' upload",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, editable=False)),
            ],
            options={
                "verbose_name": "paper check rule",
                "ordering": ["order", "code"],
            },
        ),
    ]
