# Generated by Django 5.2.17 on 2026-09-25 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0016_check_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="checklimits",
            name="keywords_from_list",
            field=models.PositiveIntegerField(
                default=3,
                help_text="0 switches this check off.",
                verbose_name="keywords from the suggested list (at least)",
            ),
        ),
        migrations.AddField(
            model_name="checklimits",
            name="min_image_dpi",
            field=models.PositiveIntegerField(
                default=200,
                help_text="At the size the picture is shown in the paper. The template asks for about 1,800 pixels across the full text width, which is some 280 pixels per inch.",
                verbose_name="minimum picture resolution (pixels per inch)",
            ),
        ),
        migrations.AddField(
            model_name="checklimits",
            name="paragraph_words",
            field=models.PositiveIntegerField(
                default=250, verbose_name="longest paragraph (words)"
            ),
        ),
    ]
