# Generated by Django 5.2.17 on 2026-09-23 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('archive', '0004_fill_authors_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, help_text='Shown above the members. Blank lines start new paragraphs.')),
                ('charter_section', models.CharField(blank=True, help_text='For example §9.2', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('general_secretary', 'General Secretary'), ('former_general_secretary', 'Former General Secretary'), ('moderator', 'Moderator'), ('elected', 'Elected member'), ('spare', 'Spare'), ('member', 'Member')], default='elected', max_length=40)),
                ('is_chair', models.BooleanField(default=False, verbose_name='chair')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('affiliation', models.CharField(blank=True, max_length=200)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('start_date', models.DateField(blank=True, help_text='Usually the Annual Business Meeting that elected them.', null=True)),
                ('end_date', models.DateField(blank=True, help_text='The day the term ends (for elected members usually the Annual Business Meeting three years later). Leave blank if open-ended.', null=True)),
                ('note', models.CharField(blank=True, help_text="Shown with the name, e.g. 'interim, filling a vacancy'.", max_length=200)),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='governance.committee')),
                ('person', models.ForeignKey(blank=True, help_text="Links the name to the person's author page, if they have one.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seats', to='archive.authorperson')),
            ],
            options={
                'ordering': ['committee', '-is_chair', 'last_name', 'first_name'],
            },
        ),
    ]
