# Generated by Django 5.2.17 on 2026-09-23 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0002_initial_committees'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='url',
            field=models.URLField(blank=True, help_text="The person's page at their institution.", verbose_name='profile page'),
        ),
    ]
