# Generated by Django 5.2.17 on 2026-09-24 13:16

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('governance', '0003_seat_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='committee',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='governance.committee'),
        ),
    ]
