# Generated by Django 5.2.17 on 2026-09-25 15:30

import apps.programme.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('archive', '0010_admin_clusters'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('conferences', '0005_programme_block'),
        ('production', '0018_orcid_rules_reject'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('hidden', 'Hidden (being prepared)'), ('provisional', 'Provisional (public, may change)'), ('final', 'Final')], default='hidden', help_text='Hidden: only the editors see it. Provisional: public, marked as such.', max_length=20)),
                ('time_zone', models.CharField(help_text='Where the conference takes place, e.g. Europe/Berlin. Used for calendar files.', max_length=60, validators=[apps.programme.models.validate_time_zone])),
                ('first_day', models.DateField(help_text='The first day with a session, e.g. of the PhD summer school.')),
                ('last_day', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('chairs', models.ForeignKey(blank=True, help_text='The conference chairs: they edit every part and the locations.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='auth.group')),
                ('conference', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='programme', to='archive.conference')),
            ],
            options={
                'ordering': ['-conference__number'],
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('academic', 'Academic conference'), ('industry', 'Industry day'), ('workshop', 'Workshop day'), ('phd', 'PhD summer school'), ('other', 'Other')], default='other', max_length=20)),
                ('name', models.CharField(max_length=120)),
                ('colour', models.CharField(default='#365a91', help_text="Marks the part's sessions, as #rrggbb.", max_length=7, validators=[apps.programme.models.validate_colour])),
                ('description', models.TextField(blank=True)),
                ('public', models.BooleanField(default=True, help_text='Untick to show the part only through its private link (e.g. the PhD summer school).')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('editors', models.ForeignKey(blank=True, help_text='The people who edit this part (besides the conference chairs).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='auth.group')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='programme.programme')),
            ],
            options={
                'ordering': ['programme', 'sort_order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="For example 'Room A 101' or 'Hofbräuhaus'.", max_length=200)),
                ('building', models.CharField(blank=True, max_length=200, verbose_name='building or floor')),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('map_url', models.URLField(blank=True, help_text="Mazemap, Google Maps or the venue's own map.", max_length=1000, verbose_name='map link')),
                ('address', models.CharField(blank=True, help_text='For places away from the venue.', max_length=300)),
                ('accessibility', models.CharField(blank=True, help_text="For example 'Step-free via the lift'.", max_length=300)),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Position in lists and in the grid.')),
                ('floor_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='programme.programme')),
            ],
            options={
                'ordering': ['programme', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('kind', models.CharField(choices=[('papers', 'Paper session'), ('posters', 'Poster session'), ('keynote', 'Keynote'), ('panel', 'Panel'), ('workshop', 'Workshop'), ('industry', 'Industry session'), ('break', 'Break'), ('meal', 'Meal'), ('social', 'Social event'), ('meeting', 'Meeting (e.g. the Annual Business Meeting)'), ('other', 'Other')], default='papers', max_length=20)),
                ('code', models.CharField(blank=True, help_text='Short name, e.g. 3B.', max_length=20)),
                ('title', models.CharField(blank=True, help_text="Blank: the kind of session, e.g. 'Break'.", max_length=300)),
                ('plenary', models.BooleanField(default=False, help_text='For everyone in the part: nothing runs in parallel.')),
                ('notes', models.TextField(blank=True, help_text='Shown with the session.')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('keynote', models.ForeignKey(blank=True, help_text='A speaker from the keynotes page.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='conferences.keynote')),
                ('location', models.ForeignKey(blank=True, help_text='Required, except for breaks.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='programme.location')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='programme.part')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='programme.programme')),
                ('track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='archive.conferencetrack')),
            ],
            options={
                'ordering': ['date', 'start', 'end', 'location__sort_order', 'code', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='SessionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('presentation', models.CharField(choices=[('talk', 'Talk'), ('poster', 'Poster')], default='talk', max_length=10)),
                ('presenter', models.CharField(blank=True, help_text="One of the paper's authors.", max_length=200)),
                ('title', models.CharField(blank=True, help_text='For an item that is not a paper.', max_length=300)),
                ('speaker', models.CharField(blank=True, help_text='For an item that is not a paper.', max_length=200)),
                ('minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('board', models.CharField(blank=True, max_length=20, verbose_name='poster board')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='programme.session')),
                ('submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programme_items', to='production.submission', verbose_name='paper')),
            ],
            options={
                'ordering': ['session', 'order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='SessionPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('chair', 'Chair'), ('co_chair', 'Co-chair'), ('facilitator', 'Facilitator'), ('moderator', 'Moderator'), ('panellist', 'Panellist'), ('speaker', 'Speaker')], default='chair', max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('affiliation', models.CharField(blank=True, max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
                ('person', models.ForeignKey(blank=True, help_text="Links the name to the person's author page.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='archive.authorperson')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people', to='programme.session')),
            ],
            options={
                'ordering': ['session', 'order', 'pk'],
            },
        ),
    ]
