# Generated by Django 5.2.17 on 2026-09-25 15:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0018_orcid_rules_reject'),
        ('programme', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='author_deadline',
            field=models.DateField(blank=True, help_text='By when every paper must be backed by a registration and its presentation confirmed.', null=True, verbose_name='deadline for authors'),
        ),
        migrations.AddField(
            model_name='programme',
            name='request_body',
            field=models.TextField(blank=True, verbose_name='confirmation email: text'),
        ),
        migrations.AddField(
            model_name='programme',
            name='request_subject',
            field=models.CharField(blank=True, max_length=300, verbose_name='confirmation email: subject'),
        ),
        migrations.AddField(
            model_name='programme',
            name='warning_body',
            field=models.TextField(blank=True, verbose_name='warning email: text'),
        ),
        migrations.AddField(
            model_name='programme',
            name='warning_subject',
            field=models.CharField(blank=True, max_length=300, verbose_name='warning email: subject'),
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text="The registration's ID in the export, or its email address.", max_length=200)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(max_length=300)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('paid', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True, help_text='In the latest export.')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='programme.programme')),
            ],
            options={
                'ordering': ['programme', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PaperPresentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('recipients', models.JSONField(blank=True, default=list)),
                ('requested', models.DateTimeField(blank=True, null=True)),
                ('reminded', models.DateTimeField(blank=True, null=True)),
                ('warned', models.DateTimeField(blank=True, null=True)),
                ('answer', models.CharField(blank=True, choices=[('present', 'Will be presented'), ('not_present', 'Published, not presented'), ('withdraw', 'The authors withdraw it')], max_length=20)),
                ('presenter', models.CharField(blank=True, max_length=200)),
                ('backer', models.CharField(blank=True, help_text='The author who is registered.', max_length=200, verbose_name='backed by')),
                ('backer_email', models.EmailField(blank=True, help_text='The address the backer registered with, if different.', max_length=254)),
                ('comment', models.TextField(blank=True)),
                ('responder', models.CharField(blank=True, max_length=200)),
                ('responded', models.DateTimeField(blank=True, null=True)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='presentation', to='production.submission')),
                ('registration', models.ForeignKey(blank=True, help_text='Chosen by the editors: this registration backs the paper.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='programme.registration')),
            ],
            options={
                'ordering': ['submission__conftool_id'],
            },
        ),
        migrations.CreateModel(
            name='RegistrationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('counts', models.BooleanField(default=False, help_text='A registration for the technical/academic conference.', verbose_name='backs papers')),
                ('decided', models.BooleanField(default=False, editable=False, help_text='Someone has looked at it.')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_types', to='programme.programme')),
            ],
            options={
                'ordering': ['programme', 'name'],
                'unique_together': {('programme', 'name')},
            },
        ),
        migrations.AddField(
            model_name='registration',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations', to='programme.registrationtype'),
        ),
        migrations.AlterUniqueTogether(
            name='registration',
            unique_together={('programme', 'key')},
        ),
    ]
