# Generated by Django 5.2.17 on 2026-09-25 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programme', '0003_part_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='notice',
            field=models.CharField(blank=True, help_text='A short notice at the top of every programme page, e.g. about a late change.', max_length=300),
        ),
        migrations.AddField(
            model_name='session',
            name='cancelled',
            field=models.BooleanField(default=False, help_text='Shown struck through, and cancelled in calendars.'),
        ),
        migrations.AddField(
            model_name='session',
            name='change_note',
            field=models.CharField(blank=True, help_text="A late change visitors should notice, e.g. 'Moved to Room 102' or 'Starts at 14:15'.", max_length=200),
        ),
        migrations.AddField(
            model_name='session',
            name='changed',
            field=models.DateTimeField(blank=True, editable=False, help_text='When the change note or cancellation was last set.', null=True),
        ),
    ]
