# Generated by Django 5.2.17 on 2026-09-25 16:58

import apps.programme.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programme', '0004_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='paperpresentation',
            name='slides',
            field=models.FileField(blank=True, help_text='The presentation (PDF or PowerPoint), uploaded by the authors. Public.', max_length=300, upload_to=apps.programme.models._slides_path),
        ),
        migrations.AddField(
            model_name='paperpresentation',
            name='slides_uploaded',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
