# Generated by Django 5.2.17 on 2026-09-26 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "conferences",
            "0014_speakers_block",
        ),
        ("programme", "0005_slides"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="keynote",
            field=models.ForeignKey(
                blank=True,
                help_text="A speaker from Speakers in the conference's menu.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="conferences.speaker",
            ),
        ),
    ]
