# Generated by Django 5.2.17 on 2026-09-26 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0017_dates_belong_to'),
        ('programme', '0006_session_speaker'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('welcome', 'Welcome or opening'), ('keynote', 'Keynote'), ('talk', 'Talk'), ('workshop', 'Workshop'), ('panel', 'Panel'), ('awards', 'Awards'), ('closing', 'Closing'), ('other', 'Other')], default='talk', max_length=20)),
                ('title', models.CharField(max_length=300)),
                ('speakers', models.CharField(blank=True, help_text="Who presents it, e.g. 'Ann Smith (TUM)'.", max_length=300)),
                ('description', models.TextField(blank=True)),
                ('minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contributions', to='programme.part')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='programme.programme')),
                ('speaker', models.ForeignKey(blank=True, help_text="The speaker's profile, from Speakers.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='conferences.speaker')),
            ],
            options={
                'ordering': ['programme', 'part__sort_order', 'kind', 'title'],
            },
        ),
        migrations.AddField(
            model_name='sessionitem',
            name='contribution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programme_items', to='programme.contribution'),
        ),
    ]
