# Generated by Django 5.2.17 on 2026-09-26 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programme', '0007_contributions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='location',
            field=models.ForeignKey(blank=True, help_text='Required, except for breaks and meals.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='programme.location'),
        ),
    ]
