# Generated by Django 5.2.17 on 2026-09-26 17:00

import django.db.models.deletion
from django.db import migrations, models


def from_sessions(apps, schema_editor):
    """The days that have sessions belong to the parts of those sessions."""
    Programme = apps.get_model("programme", "Programme")
    ProgrammeDay = apps.get_model("programme", "ProgrammeDay")
    for programme in Programme.objects.all():
        by_date = {}
        for date, part_id in programme.sessions.values_list("date", "part_id").distinct():
            by_date.setdefault(date, set()).add(part_id)
        for date, parts in by_date.items():
            day, _ = ProgrammeDay.objects.get_or_create(programme=programme, date=date)
            day.parts.set(parts)


class Migration(migrations.Migration):

    dependencies = [
        ('programme', '0009_days_follow_the_conference'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgrammeDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('parts', models.ManyToManyField(blank=True, related_name='days', to='programme.part')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days_set', to='programme.programme')),
            ],
            options={
                'ordering': ['programme', 'date'],
                'unique_together': {('programme', 'date')},
            },
        ),
        migrations.RunPython(from_sessions, migrations.RunPython.noop),
    ]
