# Generated by Django 5.2.17 on 2026-09-26 17:29

import django.db.models.deletion
from django.db import migrations, models


def lanes_from_rooms(apps, schema_editor):
    """Existing sessions get lanes: a room keeps its column as long as it can, and a day has as
    many lanes as it needs at the busiest time, not as many as it has rooms."""
    from apps.programme.lanes import assign

    Session = apps.get_model("programme", "Session")
    by_day = {}
    for s in Session.objects.all():
        by_day.setdefault((s.programme_id, s.date), []).append(s)
    for sessions in by_day.values():
        for session, lane in assign(sessions).items():
            Session.objects.filter(pk=session.pk).update(lane=lane)


class Migration(migrations.Migration):

    dependencies = [
        ('programme', '0010_days_belong_to_parts'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmeday',
            name='lanes',
            field=models.PositiveSmallIntegerField(blank=True, help_text='How many sessions can run in parallel on the day.', null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='lane',
            field=models.PositiveSmallIntegerField(blank=True, help_text="Which of the day's parallel lanes the session is drawn in (1, 2, 3 ...). Not a room: rooms are assigned to sessions, and may change during a day.", null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='location',
            field=models.ForeignKey(blank=True, help_text='The room. It can be assigned later: the checks list sessions without one.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='programme.location'),
        ),
        migrations.RunPython(lanes_from_rooms, migrations.RunPython.noop),
    ]
