# Generated by Django 5.2.17 on 2026-09-24 15:58

import apps.conferences.models
import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("archive", "0010_admin_clusters"),
        ("wagtailcore", "0097_baselogentry_uuid_action_timestamp_indexes"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="AcceptedPapersPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("intro", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "accepted papers page",
            },
            bases=(apps.conferences.models.ConferencePageMixin, "wagtailcore.page"),
        ),
        migrations.CreateModel(
            name="CommitteesPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("intro", models.TextField(blank=True)),
                (
                    "show_editors",
                    models.BooleanField(
                        default=True,
                        help_text="List the editors from the IGLC's conference record as 'Proceedings editors'.",
                        verbose_name="show the proceedings editors",
                    ),
                ),
            ],
            options={
                "verbose_name": "committees page",
            },
            bases=(apps.conferences.models.ConferencePageMixin, "wagtailcore.page"),
        ),
        migrations.CreateModel(
            name="ConferenceIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "intro",
                    models.TextField(
                        blank=True,
                        help_text="Shown when no conference is marked as current.",
                    ),
                ),
            ],
            options={
                "verbose_name": "conference sites (root)",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="ConferencePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "intro",
                    models.TextField(
                        blank=True,
                        help_text="One or two sentences shown under the title.",
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            ("text", 0),
                            ("image", 4),
                            ("button", 8),
                            ("embed", 9),
                            ("important_dates", 10),
                            ("tracks", 11),
                        ],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": [
                                        "h2",
                                        "h3",
                                        "h4",
                                        "bold",
                                        "italic",
                                        "superscript",
                                        "subscript",
                                        "ol",
                                        "ul",
                                        "hr",
                                        "link",
                                        "document-link",
                                        "image",
                                        "embed",
                                    ]
                                },
                            ),
                            1: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                            2: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "What the picture shows, for readers who cannot see it. Blank if decorative.",
                                    "max_length": 250,
                                    "required": False,
                                },
                            ),
                            3: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"max_length": 250, "required": False},
                            ),
                            4: (
                                "wagtail.blocks.StructBlock",
                                [[("image", 1), ("alt", 2), ("caption", 3)]],
                                {},
                            ),
                            5: ("wagtail.blocks.CharBlock", (), {"max_length": 60}),
                            6: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {"required": False},
                            ),
                            7: (
                                "wagtail.blocks.URLBlock",
                                (),
                                {
                                    "help_text": "Used when no page is chosen, e.g. the registration system.",
                                    "required": False,
                                },
                            ),
                            8: (
                                "wagtail.blocks.StructBlock",
                                [[("label", 5), ("page", 6), ("url", 7)]],
                                {},
                            ),
                            9: (
                                "wagtail.embeds.blocks.EmbedBlock",
                                (),
                                {
                                    "help_text": "A video or a map, by its address (YouTube, Vimeo...).",
                                    "icon": "media",
                                },
                            ),
                            10: (
                                "wagtail.blocks.static_block.StaticBlock",
                                (),
                                {
                                    "admin_text": "The important dates, as entered on the conference's home page.",
                                    "icon": "date",
                                    "template": "conferences/blocks/important_dates.html",
                                },
                            ),
                            11: (
                                "wagtail.blocks.static_block.StaticBlock",
                                (),
                                {
                                    "admin_text": "The conference's tracks, from the IGLC's conference record.",
                                    "icon": "list-ul",
                                    "template": "conferences/blocks/tracks.html",
                                },
                            ),
                        },
                    ),
                ),
            ],
            options={
                "verbose_name": "conference page",
            },
            bases=(apps.conferences.models.ConferencePageMixin, "wagtailcore.page"),
        ),
        migrations.CreateModel(
            name="KeynotesPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("intro", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "keynotes page",
            },
            bases=(apps.conferences.models.ConferencePageMixin, "wagtailcore.page"),
        ),
        migrations.CreateModel(
            name="SponsorsPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("intro", models.TextField(blank=True)),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            ("text", 0),
                            ("image", 4),
                            ("button", 8),
                            ("embed", 9),
                            ("important_dates", 10),
                            ("tracks", 11),
                        ],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": [
                                        "h2",
                                        "h3",
                                        "h4",
                                        "bold",
                                        "italic",
                                        "superscript",
                                        "subscript",
                                        "ol",
                                        "ul",
                                        "hr",
                                        "link",
                                        "document-link",
                                        "image",
                                        "embed",
                                    ]
                                },
                            ),
                            1: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                            2: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "What the picture shows, for readers who cannot see it. Blank if decorative.",
                                    "max_length": 250,
                                    "required": False,
                                },
                            ),
                            3: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"max_length": 250, "required": False},
                            ),
                            4: (
                                "wagtail.blocks.StructBlock",
                                [[("image", 1), ("alt", 2), ("caption", 3)]],
                                {},
                            ),
                            5: ("wagtail.blocks.CharBlock", (), {"max_length": 60}),
                            6: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {"required": False},
                            ),
                            7: (
                                "wagtail.blocks.URLBlock",
                                (),
                                {
                                    "help_text": "Used when no page is chosen, e.g. the registration system.",
                                    "required": False,
                                },
                            ),
                            8: (
                                "wagtail.blocks.StructBlock",
                                [[("label", 5), ("page", 6), ("url", 7)]],
                                {},
                            ),
                            9: (
                                "wagtail.embeds.blocks.EmbedBlock",
                                (),
                                {
                                    "help_text": "A video or a map, by its address (YouTube, Vimeo...).",
                                    "icon": "media",
                                },
                            ),
                            10: (
                                "wagtail.blocks.static_block.StaticBlock",
                                (),
                                {
                                    "admin_text": "The important dates, as entered on the conference's home page.",
                                    "icon": "date",
                                    "template": "conferences/blocks/important_dates.html",
                                },
                            ),
                            11: (
                                "wagtail.blocks.static_block.StaticBlock",
                                (),
                                {
                                    "admin_text": "The conference's tracks, from the IGLC's conference record.",
                                    "icon": "list-ul",
                                    "template": "conferences/blocks/tracks.html",
                                },
                            ),
                        },
                        help_text="For example how to become a sponsor.",
                    ),
                ),
            ],
            options={
                "verbose_name": "sponsors page",
            },
            bases=(apps.conferences.models.ConferencePageMixin, "wagtailcore.page"),
        ),
        migrations.CreateModel(
            name="CommitteeMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "committee",
                    models.CharField(
                        help_text="For example 'Organising committee' or 'Scientific committee'.",
                        max_length=120,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "role",
                    models.CharField(
                        blank=True, help_text="For example 'Chair'.", max_length=120
                    ),
                ),
                ("affiliation", models.CharField(blank=True, max_length=300)),
                ("country", models.CharField(blank=True, max_length=100)),
                (
                    "person",
                    models.ForeignKey(
                        blank=True,
                        help_text="Links the name to the person's author page.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="archive.authorperson",
                    ),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="conferences.committeespage",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ConferenceHomePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "is_current",
                    models.BooleanField(
                        default=False,
                        help_text="Served at the site's main address. Marking one conference as current unmarks the others.",
                        verbose_name="current conference",
                    ),
                ),
                (
                    "frozen",
                    models.BooleanField(
                        default=False,
                        help_text="After the conference: the pages can no longer be edited by the organisers, and the site says that the conference has taken place.",
                    ),
                ),
                (
                    "tagline",
                    models.CharField(
                        blank=True,
                        help_text="The conference theme, if there is one.",
                        max_length=200,
                    ),
                ),
                ("intro", wagtail.fields.RichTextField(blank=True)),
                (
                    "primary_colour",
                    models.CharField(
                        default="#365a91",
                        help_text="Header, links and headings, as #rrggbb. White text must be readable on it.",
                        max_length=7,
                    ),
                ),
                (
                    "accent_colour",
                    models.CharField(
                        default="#d4772a",
                        help_text="Buttons and highlights, as #rrggbb.",
                        max_length=7,
                    ),
                ),
                (
                    "heading_font",
                    models.CharField(
                        choices=[
                            ("serif", "Source Serif (IGLC default)"),
                            ("sans", "Source Sans"),
                            ("georgia", "Georgia"),
                            ("system", "The visitor's system font"),
                        ],
                        default="serif",
                        max_length=20,
                    ),
                ),
                (
                    "registration_url",
                    models.URLField(
                        blank=True,
                        help_text="The registration system. Shown as a button in the header.",
                    ),
                ),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            ("text", 0),
                            ("image", 4),
                            ("button", 8),
                            ("embed", 9),
                            ("important_dates", 10),
                            ("tracks", 11),
                        ],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": [
                                        "h2",
                                        "h3",
                                        "h4",
                                        "bold",
                                        "italic",
                                        "superscript",
                                        "subscript",
                                        "ol",
                                        "ul",
                                        "hr",
                                        "link",
                                        "document-link",
                                        "image",
                                        "embed",
                                    ]
                                },
                            ),
                            1: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                            2: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "What the picture shows, for readers who cannot see it. Blank if decorative.",
                                    "max_length": 250,
                                    "required": False,
                                },
                            ),
                            3: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"max_length": 250, "required": False},
                            ),
                            4: (
                                "wagtail.blocks.StructBlock",
                                [[("image", 1), ("alt", 2), ("caption", 3)]],
                                {},
                            ),
                            5: ("wagtail.blocks.CharBlock", (), {"max_length": 60}),
                            6: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {"required": False},
                            ),
                            7: (
                                "wagtail.blocks.URLBlock",
                                (),
                                {
                                    "help_text": "Used when no page is chosen, e.g. the registration system.",
                                    "required": False,
                                },
                            ),
                            8: (
                                "wagtail.blocks.StructBlock",
                                [[("label", 5), ("page", 6), ("url", 7)]],
                                {},
                            ),
                            9: (
                                "wagtail.embeds.blocks.EmbedBlock",
                                (),
                                {
                                    "help_text": "A video or a map, by its address (YouTube, Vimeo...).",
                                    "icon": "media",
                                },
                            ),
                            10: (
                                "wagtail.blocks.static_block.StaticBlock",
                                (),
                                {
                                    "admin_text": "The important dates, as entered on the conference's home page.",
                                    "icon": "date",
                                    "template": "conferences/blocks/important_dates.html",
                                },
                            ),
                            11: (
                                "wagtail.blocks.static_block.StaticBlock",
                                (),
                                {
                                    "admin_text": "The conference's tracks, from the IGLC's conference record.",
                                    "icon": "list-ul",
                                    "template": "conferences/blocks/tracks.html",
                                },
                            ),
                        },
                    ),
                ),
                (
                    "conference",
                    models.OneToOneField(
                        help_text="The IGLC's record of the conference: number, dates, city and tracks come from it.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="site_home",
                        to="archive.conference",
                    ),
                ),
                (
                    "hero_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="A wide photograph for the top of the home page (at least 1600 pixels wide).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "logo",
                    models.ForeignKey(
                        blank=True,
                        help_text="The conference logo, shown in the header (about 60 pixels high).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "verbose_name": "conference home page",
            },
            bases=(apps.conferences.models.ConferencePageMixin, "wagtailcore.page"),
        ),
        migrations.CreateModel(
            name="ImportantDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="For example 'Full papers due'.", max_length=200
                    ),
                ),
                ("date", models.DateField()),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="For a period, e.g. the conference days.",
                        null=True,
                    ),
                ),
                (
                    "original_date",
                    models.DateField(
                        blank=True,
                        help_text="If the deadline was extended: the old date, shown struck through.",
                        null=True,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=200)),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="important_dates",
                        to="conferences.conferencehomepage",
                    ),
                ),
            ],
            options={
                "verbose_name": "important date",
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Keynote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                ("name", models.CharField(max_length=200)),
                ("affiliation", models.CharField(blank=True, max_length=300)),
                ("talk_title", models.CharField(blank=True, max_length=300)),
                ("biography", wagtail.fields.RichTextField(blank=True)),
                ("url", models.URLField(blank=True, verbose_name="profile page")),
                (
                    "photo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="keynotes",
                        to="conferences.keynotespage",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Sponsor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "level",
                    models.CharField(
                        blank=True,
                        help_text="For example 'Gold'. Sponsors are grouped by it.",
                        max_length=60,
                    ),
                ),
                ("url", models.URLField(blank=True)),
                (
                    "logo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sponsors",
                        to="conferences.sponsorspage",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
    ]
