# Generated by Django 5.2.17 on 2026-09-24 16:54

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conferences", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StandardPageTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "page_type",
                    models.CharField(
                        choices=[
                            (
                                "ConferencePage",
                                "Ordinary page (text, pictures, buttons, dates, tracks)",
                            ),
                            ("KeynotesPage", "Keynotes (a list of speakers)"),
                            ("CommitteesPage", "Committees (a list of members)"),
                            ("SponsorsPage", "Sponsors (logos by level, and text)"),
                            (
                                "AcceptedPapersPage",
                                "Accepted papers (listed automatically)",
                            ),
                        ],
                        default="ConferencePage",
                        max_length=40,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "slug",
                    models.SlugField(
                        help_text="The last part of the address, e.g. call-for-papers → /2027/call-for-papers/.",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "intro",
                    models.TextField(
                        blank=True,
                        help_text="One or two sentences shown under the title.",
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            ("text", 0),
                            ("image", 4),
                            ("button", 8),
                            ("embed", 9),
                            ("important_dates", 10),
                            ("tracks", 11),
                        ],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": [
                                        "h2",
                                        "h3",
                                        "h4",
                                        "bold",
                                        "italic",
                                        "superscript",
                                        "subscript",
                                        "ol",
                                        "ul",
                                        "hr",
                                        "link",
                                        "document-link",
                                        "image",
                                        "embed",
                                    ]
                                },
                            ),
                            1: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                            2: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "What the picture shows, for readers who cannot see it. Blank if decorative.",
                                    "max_length": 250,
                                    "required": False,
                                },
                            ),
                            3: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"max_length": 250, "required": False},
                            ),
                            4: (
                                "wagtail.blocks.StructBlock",
                                [[("image", 1), ("alt", 2), ("caption", 3)]],
                                {},
                            ),
                            5: ("wagtail.blocks.CharBlock", (), {"max_length": 60}),
                            6: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {"required": False},
                            ),
                            7: (
                                "wagtail.blocks.URLBlock",
                                (),
                                {
                                    "help_text": "Used when no page is chosen, e.g. the registration system.",
                                    "required": False,
                                },
                            ),
                            8: (
                                "wagtail.blocks.StructBlock",
                                [[("label", 5), ("page", 6), ("url", 7)]],
                                {},
                            ),
                            9: (
                                "wagtail.embeds.blocks.EmbedBlock",
                                (),
                                {
                                    "help_text": "A video or a map, by its address (YouTube, Vimeo...).",
                                    "icon": "media",
                                },
                            ),
                            10: (
                                "wagtail.blocks.static_block.StaticBlock",
                                (),
                                {
                                    "admin_text": "The important dates, as entered on the conference's home page.",
                                    "icon": "date",
                                    "template": "conferences/blocks/important_dates.html",
                                },
                            ),
                            11: (
                                "wagtail.blocks.static_block.StaticBlock",
                                (),
                                {
                                    "admin_text": "The conference's tracks, from the IGLC's conference record.",
                                    "icon": "list-ul",
                                    "template": "conferences/blocks/tracks.html",
                                },
                            ),
                        },
                        help_text="The starting text. Only ordinary pages and the sponsors page have one.",
                    ),
                ),
                (
                    "show_in_menus",
                    models.BooleanField(default=True, verbose_name="show in the menu"),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="Untick to stop adding this page to new sites.",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Position in the menu."
                    ),
                ),
            ],
            options={
                "verbose_name": "conference standard page",
                "ordering": ["sort_order", "pk"],
            },
        ),
    ]
