# Generated by Django 5.2.17 on 2026-09-26 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conferences", "0007_chairs_edit_the_website"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conferencehomepage",
            name="hero_image",
            field=models.ForeignKey(
                blank=True,
                help_text="A wide photograph for the top of the home page: 1600 × 600 pixels, or larger in the same shape (8:3, e.g. 2400 × 900). The title sits on its left side over a darkened band, and phones show only the middle, so keep what matters in the centre; the picture's focal point (under Images) decides what stays in view.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
    ]
