# Generated by Django 5.2.17 on 2026-09-26 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conferences", "0008_hero_image_help"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="conferencehomepage",
            name="hero_darken",
            field=models.BooleanField(
                default=True,
                help_text="A dark shade over the left part of the photograph, so that white text and logos stay readable. Turn it off if your photograph is dark enough, or if your logo reads better without it.",
                verbose_name="darken the photograph",
            ),
        ),
        migrations.AddField(
            model_name="conferencehomepage",
            name="hero_logo",
            field=models.ForeignKey(
                blank=True,
                help_text="Shown large at the top of the home page, on the photograph, instead of the title. Choose a version of the logo that reads well on your photograph. Without it, the title is shown.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="logo on the photograph",
            ),
        ),
        migrations.AddField(
            model_name="conferencehomepage",
            name="icon",
            field=models.ForeignKey(
                blank=True,
                help_text="A square image, at least 512 × 512 pixels: the browser tab and the icon when someone adds the website to a phone's home screen. Without it, the IGLC symbol is used.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AddField(
            model_name="conferencehomepage",
            name="logo_on_light",
            field=models.ForeignKey(
                blank=True,
                help_text="Used where the conference is shown on a white or light background: its page in the IGLC's proceedings archive, and link previews when the photograph is not set. Choose a version of the logo that reads well on white.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="logo on light backgrounds",
            ),
        ),
        migrations.AlterField(
            model_name="conferencehomepage",
            name="logo",
            field=models.ForeignKey(
                blank=True,
                help_text="Shown in the header of every page, on the conference's main colour, about 60 pixels high, with the place and dates next to it. Choose a version of the logo that reads well on that colour; a wide one suits the header best.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="logo in the header",
            ),
        ),
    ]
