# Generated by Django 5.2.17 on 2026-09-26 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archive", "0011_proceedings_in_archive_label"),
        ("conferences", "0009_more_logos"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="committeemember",
            name="photo",
            field=models.ForeignKey(
                blank=True,
                help_text="A portrait, at least 400 × 400 pixels; shown round, cut to a square around the picture's focal point. Without one, the initials are shown.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AddField(
            model_name="committeemember",
            name="url",
            field=models.URLField(
                blank=True,
                help_text="The person's page at their university or company, or on LinkedIn.",
                verbose_name="profile page",
            ),
        ),
        migrations.AlterField(
            model_name="committeemember",
            name="person",
            field=models.ForeignKey(
                blank=True,
                help_text="The person's author page in the IGLC proceedings, if they have one (used when no profile page is given).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="archive.authorperson",
            ),
        ),
        migrations.AlterField(
            model_name="conferencehomepage",
            name="primary_colour",
            field=models.CharField(
                default="#365a91",
                help_text="The header, the top of the home page and the contact band. The text on it is white or black, whichever reads better. Links and headings use it too, or a darker shade of it if it is too light for text on white.",
                max_length=7,
            ),
        ),
    ]
