# Generated by Django 5.2.17 on 2026-09-26 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("conferences", "0010_committee_photos"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="committeespage",
            name="show_editors",
        ),
    ]
