# Generated by Django 5.2.17 on 2026-09-26 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conferences", "0011_no_editors_on_committees"),
    ]

    operations = [
        migrations.AddField(
            model_name="committeespage",
            name="layout",
            field=models.CharField(
                choices=[
                    (
                        "sections",
                        "Each committee below the previous one, with large portraits",
                    ),
                    ("columns", "Committees side by side, with small portraits"),
                    ("compact", "Committees side by side, names only"),
                ],
                default="sections",
                help_text="Side by side suits several small committees; below each other suits a few committees with portraits.",
                max_length=20,
            ),
        ),
    ]
