"""The Speakers block; the keynotes pages become ordinary pages with it (see 0013)."""

import json
import uuid

# Generated by Django 5.2.17 on 2026-09-26 13:28

import wagtail.fields
from django.db import migrations, models


GROUP = "Keynote speakers"


def _body():
    return [{"type": "speakers", "value": {"group": GROUP}, "id": str(uuid.uuid4())}]


def convert_pages(apps, schema_editor):
    ContentType = apps.get_model("contenttypes", "ContentType")
    Page = apps.get_model("wagtailcore", "Page")
    Revision = apps.get_model("wagtailcore", "Revision")
    KeynotesPage = apps.get_model("conferences", "KeynotesPage")
    ConferencePage = apps.get_model("conferences", "ConferencePage")
    Template = apps.get_model("conferences", "StandardPageTemplate")
    ordinary, _ = ContentType.objects.get_or_create(app_label="conferences", model="conferencepage")
    old = ContentType.objects.filter(app_label="conferences", model="keynotespage").first()
    connection = schema_editor.connection
    table = connection.ops.quote_name(KeynotesPage._meta.db_table)
    for keynotes in KeynotesPage.objects.all():
        pk, intro = keynotes.pk, keynotes.intro
        body = _body()
        with connection.cursor() as cursor:
            cursor.execute(f"DELETE FROM {table} WHERE page_ptr_id = %s", [pk])
        page = ConferencePage(page_ptr_id=pk, intro=intro, body=json.dumps(body))
        page.save_base(raw=True)
        Page.objects.filter(pk=pk).update(content_type=ordinary)
        revisions = Revision.objects.filter(object_id=str(pk))
        if old is not None:
            revisions = revisions.filter(content_type=old)
        for revision in revisions:
            content = dict(revision.content)
            content["content_type"] = ordinary.pk
            content.pop("keynotes", None)
            content.setdefault("body", json.dumps(body))
            revision.content = content
            revision.content_type = ordinary
            revision.save(update_fields=["content", "content_type"])
    for template in Template.objects.filter(page_type="KeynotesPage"):
        template.page_type = "ConferencePage"
        template.body = json.dumps(_body())
        template.save()


class Migration(migrations.Migration):

    dependencies = [
        ("conferences", "0013_speakers"),
        ("wagtailcore", "0094_alter_page_locale"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="speaker",
            options={"ordering": ["sort_order"], "verbose_name": "speaker"},
        ),
        migrations.AlterField(
            model_name="conferencehomepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("text", 0),
                    ("image", 4),
                    ("button", 8),
                    ("embed", 9),
                    ("important_dates", 10),
                    ("tracks", 11),
                    ("programme", 13),
                    ("speakers", 15),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "h2",
                                "h3",
                                "h4",
                                "bold",
                                "italic",
                                "superscript",
                                "subscript",
                                "ol",
                                "ul",
                                "hr",
                                "link",
                                "document-link",
                                "image",
                                "embed",
                            ]
                        },
                    ),
                    1: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "What the picture shows, for readers who cannot see it. Blank if decorative.",
                            "max_length": 250,
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 250, "required": False},
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 1), ("alt", 2), ("caption", 3)]],
                        {},
                    ),
                    5: ("wagtail.blocks.CharBlock", (), {"max_length": 60}),
                    6: ("wagtail.blocks.PageChooserBlock", (), {"required": False}),
                    7: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Used when no page is chosen, e.g. the registration system.",
                            "required": False,
                        },
                    ),
                    8: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 5), ("page", 6), ("url", 7)]],
                        {},
                    ),
                    9: (
                        "wagtail.embeds.blocks.EmbedBlock",
                        (),
                        {
                            "help_text": "A video or a map, by its address (YouTube, Vimeo...).",
                            "icon": "media",
                        },
                    ),
                    10: (
                        "wagtail.blocks.static_block.StaticBlock",
                        (),
                        {
                            "admin_text": "The important dates, as entered on the conference's home page.",
                            "icon": "date",
                            "template": "conferences/blocks/important_dates.html",
                        },
                    ),
                    11: (
                        "wagtail.blocks.static_block.StaticBlock",
                        (),
                        {
                            "admin_text": "The conference's tracks, from the IGLC's conference record.",
                            "icon": "list-ul",
                            "template": "conferences/blocks/tracks.html",
                        },
                    ),
                    12: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("academic", "Academic conference"),
                                ("industry", "Industry day"),
                                ("workshop", "Workshop day"),
                                ("phd", "PhD summer school"),
                                ("other", "Other parts"),
                            ],
                            "help_text": "Blank: every public part.",
                            "required": False,
                        },
                    ),
                    13: ("wagtail.blocks.StructBlock", [[("part", 12)]], {}),
                    14: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Which speakers, as grouped under Speakers (for example 'Keynote speakers'). Blank: all, under the names of their groups.",
                            "required": False,
                        },
                    ),
                    15: ("wagtail.blocks.StructBlock", [[("group", 14)]], {}),
                },
            ),
        ),
        migrations.AlterField(
            model_name="conferencepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("text", 0),
                    ("image", 4),
                    ("button", 8),
                    ("embed", 9),
                    ("important_dates", 10),
                    ("tracks", 11),
                    ("programme", 13),
                    ("speakers", 15),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "h2",
                                "h3",
                                "h4",
                                "bold",
                                "italic",
                                "superscript",
                                "subscript",
                                "ol",
                                "ul",
                                "hr",
                                "link",
                                "document-link",
                                "image",
                                "embed",
                            ]
                        },
                    ),
                    1: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "What the picture shows, for readers who cannot see it. Blank if decorative.",
                            "max_length": 250,
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 250, "required": False},
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 1), ("alt", 2), ("caption", 3)]],
                        {},
                    ),
                    5: ("wagtail.blocks.CharBlock", (), {"max_length": 60}),
                    6: ("wagtail.blocks.PageChooserBlock", (), {"required": False}),
                    7: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Used when no page is chosen, e.g. the registration system.",
                            "required": False,
                        },
                    ),
                    8: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 5), ("page", 6), ("url", 7)]],
                        {},
                    ),
                    9: (
                        "wagtail.embeds.blocks.EmbedBlock",
                        (),
                        {
                            "help_text": "A video or a map, by its address (YouTube, Vimeo...).",
                            "icon": "media",
                        },
                    ),
                    10: (
                        "wagtail.blocks.static_block.StaticBlock",
                        (),
                        {
                            "admin_text": "The important dates, as entered on the conference's home page.",
                            "icon": "date",
                            "template": "conferences/blocks/important_dates.html",
                        },
                    ),
                    11: (
                        "wagtail.blocks.static_block.StaticBlock",
                        (),
                        {
                            "admin_text": "The conference's tracks, from the IGLC's conference record.",
                            "icon": "list-ul",
                            "template": "conferences/blocks/tracks.html",
                        },
                    ),
                    12: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("academic", "Academic conference"),
                                ("industry", "Industry day"),
                                ("workshop", "Workshop day"),
                                ("phd", "PhD summer school"),
                                ("other", "Other parts"),
                            ],
                            "help_text": "Blank: every public part.",
                            "required": False,
                        },
                    ),
                    13: ("wagtail.blocks.StructBlock", [[("part", 12)]], {}),
                    14: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Which speakers, as grouped under Speakers (for example 'Keynote speakers'). Blank: all, under the names of their groups.",
                            "required": False,
                        },
                    ),
                    15: ("wagtail.blocks.StructBlock", [[("group", 14)]], {}),
                },
            ),
        ),
        migrations.AlterField(
            model_name="sponsorspage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("text", 0),
                    ("image", 4),
                    ("button", 8),
                    ("embed", 9),
                    ("important_dates", 10),
                    ("tracks", 11),
                    ("programme", 13),
                    ("speakers", 15),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "h2",
                                "h3",
                                "h4",
                                "bold",
                                "italic",
                                "superscript",
                                "subscript",
                                "ol",
                                "ul",
                                "hr",
                                "link",
                                "document-link",
                                "image",
                                "embed",
                            ]
                        },
                    ),
                    1: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "What the picture shows, for readers who cannot see it. Blank if decorative.",
                            "max_length": 250,
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 250, "required": False},
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 1), ("alt", 2), ("caption", 3)]],
                        {},
                    ),
                    5: ("wagtail.blocks.CharBlock", (), {"max_length": 60}),
                    6: ("wagtail.blocks.PageChooserBlock", (), {"required": False}),
                    7: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Used when no page is chosen, e.g. the registration system.",
                            "required": False,
                        },
                    ),
                    8: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 5), ("page", 6), ("url", 7)]],
                        {},
                    ),
                    9: (
                        "wagtail.embeds.blocks.EmbedBlock",
                        (),
                        {
                            "help_text": "A video or a map, by its address (YouTube, Vimeo...).",
                            "icon": "media",
                        },
                    ),
                    10: (
                        "wagtail.blocks.static_block.StaticBlock",
                        (),
                        {
                            "admin_text": "The important dates, as entered on the conference's home page.",
                            "icon": "date",
                            "template": "conferences/blocks/important_dates.html",
                        },
                    ),
                    11: (
                        "wagtail.blocks.static_block.StaticBlock",
                        (),
                        {
                            "admin_text": "The conference's tracks, from the IGLC's conference record.",
                            "icon": "list-ul",
                            "template": "conferences/blocks/tracks.html",
                        },
                    ),
                    12: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("academic", "Academic conference"),
                                ("industry", "Industry day"),
                                ("workshop", "Workshop day"),
                                ("phd", "PhD summer school"),
                                ("other", "Other parts"),
                            ],
                            "help_text": "Blank: every public part.",
                            "required": False,
                        },
                    ),
                    13: ("wagtail.blocks.StructBlock", [[("part", 12)]], {}),
                    14: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Which speakers, as grouped under Speakers (for example 'Keynote speakers'). Blank: all, under the names of their groups.",
                            "required": False,
                        },
                    ),
                    15: ("wagtail.blocks.StructBlock", [[("group", 14)]], {}),
                },
                help_text="For example how to become a sponsor.",
            ),
        ),
        migrations.AlterField(
            model_name="standardpagetemplate",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("text", 0),
                    ("image", 4),
                    ("button", 8),
                    ("embed", 9),
                    ("important_dates", 10),
                    ("tracks", 11),
                    ("programme", 13),
                    ("speakers", 15),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "h2",
                                "h3",
                                "h4",
                                "bold",
                                "italic",
                                "superscript",
                                "subscript",
                                "ol",
                                "ul",
                                "hr",
                                "link",
                                "document-link",
                                "image",
                                "embed",
                            ]
                        },
                    ),
                    1: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "What the picture shows, for readers who cannot see it. Blank if decorative.",
                            "max_length": 250,
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 250, "required": False},
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 1), ("alt", 2), ("caption", 3)]],
                        {},
                    ),
                    5: ("wagtail.blocks.CharBlock", (), {"max_length": 60}),
                    6: ("wagtail.blocks.PageChooserBlock", (), {"required": False}),
                    7: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Used when no page is chosen, e.g. the registration system.",
                            "required": False,
                        },
                    ),
                    8: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 5), ("page", 6), ("url", 7)]],
                        {},
                    ),
                    9: (
                        "wagtail.embeds.blocks.EmbedBlock",
                        (),
                        {
                            "help_text": "A video or a map, by its address (YouTube, Vimeo...).",
                            "icon": "media",
                        },
                    ),
                    10: (
                        "wagtail.blocks.static_block.StaticBlock",
                        (),
                        {
                            "admin_text": "The important dates, as entered on the conference's home page.",
                            "icon": "date",
                            "template": "conferences/blocks/important_dates.html",
                        },
                    ),
                    11: (
                        "wagtail.blocks.static_block.StaticBlock",
                        (),
                        {
                            "admin_text": "The conference's tracks, from the IGLC's conference record.",
                            "icon": "list-ul",
                            "template": "conferences/blocks/tracks.html",
                        },
                    ),
                    12: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("academic", "Academic conference"),
                                ("industry", "Industry day"),
                                ("workshop", "Workshop day"),
                                ("phd", "PhD summer school"),
                                ("other", "Other parts"),
                            ],
                            "help_text": "Blank: every public part.",
                            "required": False,
                        },
                    ),
                    13: ("wagtail.blocks.StructBlock", [[("part", 12)]], {}),
                    14: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Which speakers, as grouped under Speakers (for example 'Keynote speakers'). Blank: all, under the names of their groups.",
                            "required": False,
                        },
                    ),
                    15: ("wagtail.blocks.StructBlock", [[("group", 14)]], {}),
                },
                help_text="The starting text. Only ordinary pages and the sponsors page have one.",
            ),
        ),
        migrations.AlterField(
            model_name="standardpagetemplate",
            name="page_type",
            field=models.CharField(
                choices=[
                    (
                        "ConferencePage",
                        "Ordinary page (text, pictures, buttons, dates, tracks, speakers, programme)",
                    ),
                    ("CommitteesPage", "Committees (a list of members)"),
                    ("SponsorsPage", "Sponsors (logos by level, and text)"),
                    ("AcceptedPapersPage", "Accepted papers (listed automatically)"),
                ],
                default="ConferencePage",
                max_length=40,
            ),
        ),
        migrations.RunPython(convert_pages, migrations.RunPython.noop),
        migrations.DeleteModel("KeynotesPage"),
    ]
