# Generated by Django 5.2.17 on 2026-09-26 15:14

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conferences", "0016_main_events"),
    ]

    operations = [
        migrations.AddField(
            model_name="importantdate",
            name="belongs_to",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "General"),
                    ("papers", "Papers (submission, review)"),
                    ("registration", "Registration"),
                    ("industry", "Industry day"),
                    ("workshop", "Workshop day"),
                    ("phd", "PhD summer school"),
                ],
                default="",
                help_text="An Important dates block can show only the dates of one part: the call for papers page, say, the paper deadlines.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="conferencehomepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("text", 0),
                    ("image", 4),
                    ("button", 8),
                    ("embed", 9),
                    ("important_dates", 11),
                    ("tracks", 12),
                    ("programme", 14),
                    ("speakers", 16),
                    ("main_events", 17),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "h2",
                                "h3",
                                "h4",
                                "bold",
                                "italic",
                                "superscript",
                                "subscript",
                                "ol",
                                "ul",
                                "hr",
                                "link",
                                "document-link",
                                "image",
                                "embed",
                            ]
                        },
                    ),
                    1: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "What the picture shows, for readers who cannot see it. Blank if decorative.",
                            "max_length": 250,
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 250, "required": False},
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 1), ("alt", 2), ("caption", 3)]],
                        {},
                    ),
                    5: ("wagtail.blocks.CharBlock", (), {"max_length": 60}),
                    6: ("wagtail.blocks.PageChooserBlock", (), {"required": False}),
                    7: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Used when no page is chosen, e.g. the registration system.",
                            "required": False,
                        },
                    ),
                    8: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 5), ("page", 6), ("url", 7)]],
                        {},
                    ),
                    9: (
                        "wagtail.embeds.blocks.EmbedBlock",
                        (),
                        {
                            "help_text": "A video or a map, by its address (YouTube, Vimeo...).",
                            "icon": "media",
                        },
                    ),
                    10: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("", "All"),
                                ("papers", "Papers (submission, review)"),
                                ("registration", "Registration"),
                                ("industry", "Industry day"),
                                ("workshop", "Workshop day"),
                                ("phd", "PhD summer school"),
                                ("general", "General dates only"),
                            ],
                            "help_text": "Which dates to show. All: every date. The others: only the dates marked as belonging to it under Dates and links.",
                            "required": False,
                        },
                    ),
                    11: ("wagtail.blocks.StructBlock", [[("belongs_to", 10)]], {}),
                    12: (
                        "wagtail.blocks.static_block.StaticBlock",
                        (),
                        {
                            "admin_text": "The conference's tracks, from the IGLC's conference record.",
                            "icon": "list-ul",
                            "template": "conferences/blocks/tracks.html",
                        },
                    ),
                    13: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("academic", "Academic conference"),
                                ("industry", "Industry day"),
                                ("workshop", "Workshop day"),
                                ("phd", "PhD summer school"),
                                ("other", "Other parts"),
                            ],
                            "help_text": "Blank: every public part.",
                            "required": False,
                        },
                    ),
                    14: ("wagtail.blocks.StructBlock", [[("part", 13)]], {}),
                    15: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Which speakers, as grouped under Speakers (for example 'Keynote speakers'). Blank: all, under the names of their groups.",
                            "required": False,
                        },
                    ),
                    16: ("wagtail.blocks.StructBlock", [[("group", 15)]], {}),
                    17: (
                        "wagtail.blocks.static_block.StaticBlock",
                        (),
                        {
                            "admin_text": "The main events (under Dates and links, ticked as main events), as cards with their dates. The programme block shows them too until the detailed programme is published.",
                            "icon": "date",
                            "label": "Main events",
                            "template": "conferences/blocks/main_events.html",
                        },
                    ),
                },
            ),
        ),
        migrations.AlterField(
            model_name="conferencepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("text", 0),
                    ("image", 4),
                    ("button", 8),
                    ("embed", 9),
                    ("important_dates", 11),
                    ("tracks", 12),
                    ("programme", 14),
                    ("speakers", 16),
                    ("main_events", 17),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "h2",
                                "h3",
                                "h4",
                                "bold",
                                "italic",
                                "superscript",
                                "subscript",
                                "ol",
                                "ul",
                                "hr",
                                "link",
                                "document-link",
                                "image",
                                "embed",
                            ]
                        },
                    ),
                    1: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "What the picture shows, for readers who cannot see it. Blank if decorative.",
                            "max_length": 250,
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 250, "required": False},
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 1), ("alt", 2), ("caption", 3)]],
                        {},
                    ),
                    5: ("wagtail.blocks.CharBlock", (), {"max_length": 60}),
                    6: ("wagtail.blocks.PageChooserBlock", (), {"required": False}),
                    7: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Used when no page is chosen, e.g. the registration system.",
                            "required": False,
                        },
                    ),
                    8: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 5), ("page", 6), ("url", 7)]],
                        {},
                    ),
                    9: (
                        "wagtail.embeds.blocks.EmbedBlock",
                        (),
                        {
                            "help_text": "A video or a map, by its address (YouTube, Vimeo...).",
                            "icon": "media",
                        },
                    ),
                    10: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("", "All"),
                                ("papers", "Papers (submission, review)"),
                                ("registration", "Registration"),
                                ("industry", "Industry day"),
                                ("workshop", "Workshop day"),
                                ("phd", "PhD summer school"),
                                ("general", "General dates only"),
                            ],
                            "help_text": "Which dates to show. All: every date. The others: only the dates marked as belonging to it under Dates and links.",
                            "required": False,
                        },
                    ),
                    11: ("wagtail.blocks.StructBlock", [[("belongs_to", 10)]], {}),
                    12: (
                        "wagtail.blocks.static_block.StaticBlock",
                        (),
                        {
                            "admin_text": "The conference's tracks, from the IGLC's conference record.",
                            "icon": "list-ul",
                            "template": "conferences/blocks/tracks.html",
                        },
                    ),
                    13: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("academic", "Academic conference"),
                                ("industry", "Industry day"),
                                ("workshop", "Workshop day"),
                                ("phd", "PhD summer school"),
                                ("other", "Other parts"),
                            ],
                            "help_text": "Blank: every public part.",
                            "required": False,
                        },
                    ),
                    14: ("wagtail.blocks.StructBlock", [[("part", 13)]], {}),
                    15: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Which speakers, as grouped under Speakers (for example 'Keynote speakers'). Blank: all, under the names of their groups.",
                            "required": False,
                        },
                    ),
                    16: ("wagtail.blocks.StructBlock", [[("group", 15)]], {}),
                    17: (
                        "wagtail.blocks.static_block.StaticBlock",
                        (),
                        {
                            "admin_text": "The main events (under Dates and links, ticked as main events), as cards with their dates. The programme block shows them too until the detailed programme is published.",
                            "icon": "date",
                            "label": "Main events",
                            "template": "conferences/blocks/main_events.html",
                        },
                    ),
                },
            ),
        ),
        migrations.AlterField(
            model_name="sponsorspage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("text", 0),
                    ("image", 4),
                    ("button", 8),
                    ("embed", 9),
                    ("important_dates", 11),
                    ("tracks", 12),
                    ("programme", 14),
                    ("speakers", 16),
                    ("main_events", 17),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "h2",
                                "h3",
                                "h4",
                                "bold",
                                "italic",
                                "superscript",
                                "subscript",
                                "ol",
                                "ul",
                                "hr",
                                "link",
                                "document-link",
                                "image",
                                "embed",
                            ]
                        },
                    ),
                    1: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "What the picture shows, for readers who cannot see it. Blank if decorative.",
                            "max_length": 250,
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 250, "required": False},
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 1), ("alt", 2), ("caption", 3)]],
                        {},
                    ),
                    5: ("wagtail.blocks.CharBlock", (), {"max_length": 60}),
                    6: ("wagtail.blocks.PageChooserBlock", (), {"required": False}),
                    7: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Used when no page is chosen, e.g. the registration system.",
                            "required": False,
                        },
                    ),
                    8: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 5), ("page", 6), ("url", 7)]],
                        {},
                    ),
                    9: (
                        "wagtail.embeds.blocks.EmbedBlock",
                        (),
                        {
                            "help_text": "A video or a map, by its address (YouTube, Vimeo...).",
                            "icon": "media",
                        },
                    ),
                    10: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("", "All"),
                                ("papers", "Papers (submission, review)"),
                                ("registration", "Registration"),
                                ("industry", "Industry day"),
                                ("workshop", "Workshop day"),
                                ("phd", "PhD summer school"),
                                ("general", "General dates only"),
                            ],
                            "help_text": "Which dates to show. All: every date. The others: only the dates marked as belonging to it under Dates and links.",
                            "required": False,
                        },
                    ),
                    11: ("wagtail.blocks.StructBlock", [[("belongs_to", 10)]], {}),
                    12: (
                        "wagtail.blocks.static_block.StaticBlock",
                        (),
                        {
                            "admin_text": "The conference's tracks, from the IGLC's conference record.",
                            "icon": "list-ul",
                            "template": "conferences/blocks/tracks.html",
                        },
                    ),
                    13: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("academic", "Academic conference"),
                                ("industry", "Industry day"),
                                ("workshop", "Workshop day"),
                                ("phd", "PhD summer school"),
                                ("other", "Other parts"),
                            ],
                            "help_text": "Blank: every public part.",
                            "required": False,
                        },
                    ),
                    14: ("wagtail.blocks.StructBlock", [[("part", 13)]], {}),
                    15: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Which speakers, as grouped under Speakers (for example 'Keynote speakers'). Blank: all, under the names of their groups.",
                            "required": False,
                        },
                    ),
                    16: ("wagtail.blocks.StructBlock", [[("group", 15)]], {}),
                    17: (
                        "wagtail.blocks.static_block.StaticBlock",
                        (),
                        {
                            "admin_text": "The main events (under Dates and links, ticked as main events), as cards with their dates. The programme block shows them too until the detailed programme is published.",
                            "icon": "date",
                            "label": "Main events",
                            "template": "conferences/blocks/main_events.html",
                        },
                    ),
                },
                help_text="For example how to become a sponsor.",
            ),
        ),
        migrations.AlterField(
            model_name="standardpagetemplate",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("text", 0),
                    ("image", 4),
                    ("button", 8),
                    ("embed", 9),
                    ("important_dates", 11),
                    ("tracks", 12),
                    ("programme", 14),
                    ("speakers", 16),
                    ("main_events", 17),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "h2",
                                "h3",
                                "h4",
                                "bold",
                                "italic",
                                "superscript",
                                "subscript",
                                "ol",
                                "ul",
                                "hr",
                                "link",
                                "document-link",
                                "image",
                                "embed",
                            ]
                        },
                    ),
                    1: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "What the picture shows, for readers who cannot see it. Blank if decorative.",
                            "max_length": 250,
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 250, "required": False},
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 1), ("alt", 2), ("caption", 3)]],
                        {},
                    ),
                    5: ("wagtail.blocks.CharBlock", (), {"max_length": 60}),
                    6: ("wagtail.blocks.PageChooserBlock", (), {"required": False}),
                    7: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Used when no page is chosen, e.g. the registration system.",
                            "required": False,
                        },
                    ),
                    8: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 5), ("page", 6), ("url", 7)]],
                        {},
                    ),
                    9: (
                        "wagtail.embeds.blocks.EmbedBlock",
                        (),
                        {
                            "help_text": "A video or a map, by its address (YouTube, Vimeo...).",
                            "icon": "media",
                        },
                    ),
                    10: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("", "All"),
                                ("papers", "Papers (submission, review)"),
                                ("registration", "Registration"),
                                ("industry", "Industry day"),
                                ("workshop", "Workshop day"),
                                ("phd", "PhD summer school"),
                                ("general", "General dates only"),
                            ],
                            "help_text": "Which dates to show. All: every date. The others: only the dates marked as belonging to it under Dates and links.",
                            "required": False,
                        },
                    ),
                    11: ("wagtail.blocks.StructBlock", [[("belongs_to", 10)]], {}),
                    12: (
                        "wagtail.blocks.static_block.StaticBlock",
                        (),
                        {
                            "admin_text": "The conference's tracks, from the IGLC's conference record.",
                            "icon": "list-ul",
                            "template": "conferences/blocks/tracks.html",
                        },
                    ),
                    13: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("academic", "Academic conference"),
                                ("industry", "Industry day"),
                                ("workshop", "Workshop day"),
                                ("phd", "PhD summer school"),
                                ("other", "Other parts"),
                            ],
                            "help_text": "Blank: every public part.",
                            "required": False,
                        },
                    ),
                    14: ("wagtail.blocks.StructBlock", [[("part", 13)]], {}),
                    15: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Which speakers, as grouped under Speakers (for example 'Keynote speakers'). Blank: all, under the names of their groups.",
                            "required": False,
                        },
                    ),
                    16: ("wagtail.blocks.StructBlock", [[("group", 15)]], {}),
                    17: (
                        "wagtail.blocks.static_block.StaticBlock",
                        (),
                        {
                            "admin_text": "The main events (under Dates and links, ticked as main events), as cards with their dates. The programme block shows them too until the detailed programme is published.",
                            "icon": "date",
                            "label": "Main events",
                            "template": "conferences/blocks/main_events.html",
                        },
                    ),
                },
                help_text="The starting text. Only ordinary pages and the sponsors page have one.",
            ),
        ),
    ]
