# Generated by Django 5.2.17 on 2026-09-24 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('archive', '0010_admin_clusters'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(max_length=100, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('test', models.BooleanField(help_text="Sent to Crossref's test system (nothing is registered).")),
                ('xml', models.TextField()),
                ('papers', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('made', 'Made, not sent'), ('sent', 'Sent, waiting for Crossref'), ('success', 'Registered'), ('warning', 'Registered with warnings'), ('failed', 'Failed')], default='made', max_length=10)),
                ('sent', models.DateTimeField(blank=True, null=True)),
                ('checked', models.DateTimeField(blank=True, null=True)),
                ('response', models.TextField(blank=True, help_text="Crossref's answer to the upload.")),
                ('result', models.TextField(blank=True, help_text="Crossref's result (the submission log).")),
                ('successes', models.PositiveIntegerField(default=0)),
                ('warnings', models.PositiveIntegerField(default=0)),
                ('failures', models.PositiveIntegerField(default=0)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crossref_deposits', to='archive.conference')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
